openapi: 3.0.0
info:
  title: Cat Facts - Demo
  description: This is the cat facts API
  version: 2.0.0
  contact:
    name: Nick Berger
    email: nicholas.berger@postman.com
    url: www.nick.com
  license:
    name: Cat Facts license
    url: https://catfact.ninja
  termsOfService: CatFactsTerms
servers:
  - url: https://catfact.ninja
    description: Production server
paths:
  "/breeds":
    get:
      tags:
      - Breeds
      summary: Get a list of breeds
      description: Returns a a list of breeds
      operationId: getBreeds
      parameters:
      - name: limit
        in: query
        description: limit the amount of results returned
        required: false
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Breed"
  "/fact":
    get:
      tags:
      - Facts
      summary: Get Random Fact
      description: Returns a random fact
      operationId: getRandomFact
      parameters:
      - name: max_length
        in: query
        description: maximum length of returned fact
        required: false
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/CatFact"
        '404':
          description: Fact not found
          content:
            application/problem+json:
              schema:
                description: Not Found
                $ref: "#/components/schemas/ExampleError"

  "/facts":
    get:
      tags:
      - Facts
      summary: Get a list of facts
      description: Returns a a list of facts
      operationId: getFacts
      parameters:
      - name: max_length
        in: query
        description: maximum length of returned fact
        required: false
        schema:
          type: integer
          format: int64
      - name: limit
        in: query
        description: limit the amount of results returned
        required: false
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/CatFact"
components:
  schemas:
    Breed:
      title: Breed model
      description: Breed
      properties:
        breed:
          title: Breed
          description: Breed
          type: string
          format: string
        country:
          title: Country
          description: Country
          type: string
          format: string
        origin:
          title: Origin
          description: Origin
          type: string
          format: string
        coat:
          title: Coat
          description: Coat
          type: string
          format: string
        pattern:
          title: Pattern
          description: Pattern
          type: string
          format: string
      type: object
    CatFact:
      title: CatFact model
      description: CatFact
      properties:
        fact:
          title: Fact
          description: Fact
          type: string
          format: string
        length:
          title: Length
          description: Length
          type: integer
          format: int32
      type: object
    ExampleError:
      title: Error Response
      description: This is an example error response
      properties:
        title:
          description: The generic title for the error's description
          type: string
          format: string
          example: Internal Server Error
        detail:
          description: Details about the error message
          type: string
          format: string
          example: An error occurred while retrieving APIs
        type:
          description: The type of error
          type: string
          format: string
          example: about:blank
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
security:
  - basicAuth: []
